(() => {
  'use strict';
  const typeLabels={'web-app':'Webアプリ','chrome-extension':'Chrome拡張','learning-tool':'学習ツール','design-system':'設計ガイド','content-page':'コンテンツページ','data-tool':'分析・データ','utility':'便利ツール','experiment':'実験'};
  const statusLabels={development:'開発中',active:'運用中',prototype:'試作中',dormant:'休止中',legacy:'初期記録'};
  const docLabels={verified:'内容確認済み',inferred:'概要を仮整理',unreviewed:'思い出し待ち'};
  const selected=new Set();
  let ready=false;
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const attr=v=>esc(v).replace(/'/g,'&#39;');
  const norm=v=>String(v||'').toLowerCase().normalize('NFKC').replace(/\s+/g,'');
  const date=v=>{if(!v)return'要確認';const m=String(v).match(/^(\d{4})(?:-(\d{2}))?(?:-(\d{2}))?/);if(!m)return String(v);return m[3]?`${Number(m[1])}年${Number(m[2])}月${Number(m[3])}日`:m[2]?`${Number(m[1])}年${Number(m[2])}月`:`${m[1]}年`};
  const projects=()=>window.BUILD_DIARY_DATA?.projects||[];
  const currentView=()=>document.querySelector('[data-view-button].is-active')?.getAttribute('data-view-button')||'';
  const controls=()=>({search:document.querySelector('[data-cat-search]'),verb:document.querySelector('[data-cat-verb]'),type:document.querySelector('[data-cat-type]'),status:document.querySelector('[data-cat-status]'),year:document.querySelector('[data-cat-year]'),doc:document.querySelector('[data-cat-doc]'),link:document.querySelector('[data-cat-link]'),sort:document.querySelector('[data-cat-sort]'),layout:document.querySelector('[data-cat-layout]')});

  function toolbarHtml(){return `<div class="catalog-toolbar" data-catalog-toolbar><input class="wide" type="search" data-cat-search placeholder="名前・困りごと・タグ・技術で探す"><select data-cat-verb><option value="">すべての目的</option></select><select data-cat-type><option value="">すべての種類</option></select><select data-cat-status><option value="">すべての状態</option></select><select data-cat-year><option value="">すべての制作年</option></select><select data-cat-doc><option value="">すべての整理状態</option></select><select data-cat-link><option value="">すべての公開状況</option><option value="live">公開ページあり</option><option value="github">GitHubあり</option><option value="both">公開ページ＋GitHub</option><option value="local">手元のみ</option></select><select data-cat-sort><option value="updated-desc">更新が新しい順</option><option value="created-desc">制作が新しい順</option><option value="created-asc">制作が古い順</option><option value="title-asc">名前順</option><option value="type-asc">種類順</option><option value="status-asc">状態順</option></select><select data-cat-layout><option value="cards">カード</option><option value="compact">コンパクト</option><option value="table">表</option></select><button class="subtle-button reset" type="button" data-cat-reset>条件を戻す</button><p class="catalog-result" data-cat-count></p></div><div class="catalog-bulk" data-cat-bulk hidden><label><input type="checkbox" data-cat-all> 表示中をまとめて選択</label><strong data-cat-selected>0件選択</strong><select data-cat-format><option value="share">共有用テキスト</option><option value="markdown">Markdown</option><option value="tsv">TSV</option><option value="json">JSON</option></select><button class="primary-action" type="button" data-cat-copy disabled>選択分をコピー</button><button class="text-action" type="button" data-cat-clear disabled>選択解除</button><span class="catalog-feedback" data-cat-feedback></span></div>`}

  function populate(){const c=controls(),ps=projects();const verbs=[...new Set(ps.flatMap(p=>p.verbs||[]))].sort((a,b)=>a.localeCompare(b,'ja'));c.verb.innerHTML='<option value="">すべての目的</option>'+verbs.map(v=>`<option>${esc(v)}</option>`).join('');const types=[...new Set(ps.map(p=>p.type))].sort();c.type.innerHTML='<option value="">すべての種類</option>'+types.map(v=>`<option value="${attr(v)}">${esc(typeLabels[v]||v)}</option>`).join('');const statuses=[...new Set(ps.map(p=>p.status))].sort();c.status.innerHTML='<option value="">すべての状態</option>'+statuses.map(v=>`<option value="${attr(v)}">${esc(statusLabels[v]||v)}</option>`).join('');const years=[...new Set(ps.map(p=>String(p.createdAt||'').slice(0,4)).filter(Boolean))].sort().reverse();c.year.innerHTML='<option value="">すべての制作年</option>'+years.map(v=>`<option value="${v}">${v}年</option>`).join('');c.doc.innerHTML='<option value="">すべての整理状態</option>'+Object.keys(docLabels).map(v=>`<option value="${v}">${docLabels[v]}</option>`).join('')}

  function filtered(){const c=controls(),q=norm(c.search.value);const list=projects().filter(p=>{const text=norm([p.title,p.subtitle,p.summary,p.friction,p.id,(p.verbs||[]).join(' '),(p.technologies||[]).join(' ')].join(' ')),live=!!p.liveUrl,gh=!!p.repositoryUrl;return(!q||text.includes(q))&&(!c.verb.value||(p.verbs||[]).includes(c.verb.value))&&(!c.type.value||p.type===c.type.value)&&(!c.status.value||p.status===c.status.value)&&(!c.year.value||String(p.createdAt||'').startsWith(c.year.value))&&(!c.doc.value||p.documentationState===c.doc.value)&&(!c.link.value||(c.link.value==='live'&&live)||(c.link.value==='github'&&gh)||(c.link.value==='both'&&live&&gh)||(c.link.value==='local'&&!live&&!gh))});const dv=v=>String(v||'').replace(/[^0-9]/g,'').padEnd(8,'0'),sort=c.sort.value;list.sort(sort==='created-asc'?(a,b)=>dv(a.createdAt).localeCompare(dv(b.createdAt)):sort==='created-desc'?(a,b)=>dv(b.createdAt).localeCompare(dv(a.createdAt)):sort==='title-asc'?(a,b)=>a.title.localeCompare(b.title,'ja'):sort==='type-asc'?(a,b)=>(typeLabels[a.type]||a.type).localeCompare(typeLabels[b.type]||b.type,'ja'):sort==='status-asc'?(a,b)=>(statusLabels[a.status]||a.status).localeCompare(statusLabels[b.status]||b.status,'ja'):(a,b)=>dv(b.updatedAt||b.createdAt).localeCompare(dv(a.updatedAt||a.createdAt)));return list}
  const check=p=>`<label class="catalog-check"><input type="checkbox" data-cat-check="${attr(p.id)}"${selected.has(p.id)?' checked':''}><span class="sr-only">${esc(p.title)}を選択</span></label>`;
  const card=p=>`<article class="catalog-card ${p.featured?'featured ':''}${selected.has(p.id)?'selected':''}" data-cat-item="${attr(p.id)}">${check(p)}<span class="catalog-kicker">${esc(typeLabels[p.type]||p.type)} / ${esc(date(p.createdAt))}</span><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p><p class="problem"><strong>困っていたこと</strong><br>${esc(p.friction)}</p><button class="catalog-open" type="button" data-project-open="${attr(p.id)}">中を読む →</button></article>`;
  const row=p=>`<article class="catalog-row ${selected.has(p.id)?'selected':''}" data-cat-item="${attr(p.id)}">${check(p)}<div><span class="catalog-kicker">${esc(typeLabels[p.type]||p.type)} / ${esc(date(p.createdAt))}</span><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p></div><div class="catalog-meta"><span class="catalog-pill">${esc(statusLabels[p.status]||p.status)}</span>${(p.verbs||[]).slice(0,2).map(v=>`<span class="catalog-pill">${esc(v)}</span>`).join('')}</div><button class="catalog-open" type="button" data-project-open="${attr(p.id)}">詳細 →</button></article>`;
  const tableRow=p=>{const links=[p.liveUrl?'公開':'',p.repositoryUrl?'GitHub':''].filter(Boolean).join(' / ')||'手元のみ';return `<tr class="${selected.has(p.id)?'selected':''}" data-cat-item="${attr(p.id)}"><td class="check-cell">${check(p)}</td><td><button class="catalog-title" type="button" data-project-open="${attr(p.id)}"><strong>${esc(p.title)}</strong><small>${esc(p.summary.slice(0,80))}</small></button></td><td>${esc(typeLabels[p.type]||p.type)}</td><td>${esc(statusLabels[p.status]||p.status)}</td><td>${esc(date(p.createdAt))}</td><td>${esc(date(p.updatedAt||p.createdAt))}</td><td>${esc(links)}</td></tr>`};

  function render(){if(currentView()!=='shelf')return;const panel=document.querySelector('[data-view-panel]'),bulk=document.querySelector('[data-cat-bulk]'),c=controls(),list=filtered();document.querySelector('[data-cat-count]').textContent=`${list.length}件表示`;bulk.hidden=false;if(!list.length){panel.innerHTML='<div class="empty-state"><h3>その棚、今は空です。</h3><p>条件を少し戻してください。</p></div>';sync(list);return}if(c.layout.value==='compact')panel.innerHTML='<div class="catalog-list">'+list.map(row).join('')+'</div>';else if(c.layout.value==='table')panel.innerHTML='<div class="catalog-table-wrap"><table class="catalog-table"><thead><tr><th class="check-cell">選択</th><th>制作物</th><th>種類</th><th>状態</th><th>制作</th><th>更新</th><th>リンク</th></tr></thead><tbody>'+list.map(tableRow).join('')+'</tbody></table></div>';else panel.innerHTML='<div class="catalog-grid">'+list.map(card).join('')+'</div>';bindRows();sync(list)}
  function bindRows(){document.querySelectorAll('[data-cat-check]').forEach(input=>input.addEventListener('change',()=>{input.checked?selected.add(input.dataset.catCheck):selected.delete(input.dataset.catCheck);render()}));document.querySelectorAll('[data-project-open]').forEach(button=>button.addEventListener('click',()=>{const id=button.getAttribute('data-project-open'),params=new URLSearchParams(location.search);params.set('project',id);history.pushState({},'',location.pathname+'?'+params.toString());location.reload()}))}
  function sync(list){const count=selected.size,all=document.querySelector('[data-cat-all]'),visible=list.filter(p=>selected.has(p.id)).length;document.querySelector('[data-cat-selected]').textContent=`${count}件選択`;document.querySelector('[data-cat-copy]').disabled=!count;document.querySelector('[data-cat-clear]').disabled=!count;all.checked=!!list.length&&visible===list.length;all.indeterminate=visible>0&&visible<list.length}
  function copyFormat(list,format){const url=p=>p.liveUrl||p.repositoryUrl||'';if(format==='markdown')return list.map(p=>url(p)?`- [${p.title}](${url(p)}) — ${p.summary}`:`- **${p.title}** — ${p.summary}`).join('\n');if(format==='tsv'){const rows=[['タイトル','概要','種類','状態','制作日','更新日','公開ページ','GitHub']];list.forEach(p=>rows.push([p.title,p.summary,typeLabels[p.type]||p.type,statusLabels[p.status]||p.status,date(p.createdAt),date(p.updatedAt||p.createdAt),p.liveUrl||'',p.repositoryUrl||'']));return rows.map(r=>r.map(v=>String(v).replace(/\t/g,' ').replace(/\r?\n/g,' ')).join('\t')).join('\n')}if(format==='json')return JSON.stringify(list.map(p=>({title:p.title,summary:p.summary,type:typeLabels[p.type]||p.type,status:statusLabels[p.status]||p.status,createdAt:p.createdAt,updatedAt:p.updatedAt||p.createdAt,liveUrl:p.liveUrl||null,repositoryUrl:p.repositoryUrl||null})),null,2);return list.map(p=>p.title+'\n'+p.summary+(url(p)?'\n'+url(p):'')).join('\n\n')}
  function copyText(text){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(text);const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();return ok?Promise.resolve():Promise.reject(new Error('copy failed'))}

  function enhance(){if(ready)return;const toolbar=document.querySelector('[data-toolbar]');if(!toolbar||!window.BUILD_DIARY_DATA){setTimeout(enhance,80);return}ready=true;toolbar.outerHTML=toolbarHtml();populate();const c=controls();Object.values(c).forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',render));document.querySelector('[data-cat-reset]').addEventListener('click',()=>{c.search.value='';c.verb.value='';c.type.value='';c.status.value='';c.year.value='';c.doc.value='';c.link.value='';c.sort.value='updated-desc';c.layout.value='cards';render()});document.querySelector('[data-cat-all]').addEventListener('change',event=>{filtered().forEach(p=>event.target.checked?selected.add(p.id):selected.delete(p.id));render()});document.querySelector('[data-cat-clear]').addEventListener('click',()=>{selected.clear();render()});document.querySelector('[data-cat-copy]').addEventListener('click',()=>{const list=projects().filter(p=>selected.has(p.id)),format=document.querySelector('[data-cat-format]').value;copyText(copyFormat(list,format)).then(()=>document.querySelector('[data-cat-feedback]').textContent=`${list.length}件コピーしました`).catch(()=>document.querySelector('[data-cat-feedback]').textContent='コピーできませんでした')});document.querySelectorAll('[data-view-button]').forEach(button=>button.addEventListener('click',()=>setTimeout(()=>{const bulk=document.querySelector('[data-cat-bulk]');if(currentView()==='shelf')render();else bulk.hidden=true},0)));window.addEventListener('popstate',()=>setTimeout(render,0));setTimeout(()=>{if(currentView()==='shelf')render()},0)}
  document.addEventListener('DOMContentLoaded',()=>setTimeout(enhance,80));
})();
