(()=>{'use strict';const $=id=>document.getElementById(id),e=$('editor'),key='textworkbench.draft.v1';let past=[],future=[],committed={text:'',start:0,end:0,scroll:0},range={start:0,end:0},target=null,composing=false,timer,toastTimer,returnFocus;
const snapshot=()=>({text:e.value,start:e.selectionStart,end:e.selectionEnd,scroll:e.scrollTop});
function persist(){try{if(e.value)localStorage.setItem(key,e.value);else localStorage.removeItem(key)}catch{if(!persist.warned){persist.warned=true;notify('自動復元はこのブラウザで利用できません')}}}
function capture(){if(document.activeElement===e){range={start:e.selectionStart,end:e.selectionEnd};update()}}
function update(){const chars=Array.from(e.value).length;$('stats').textContent=`${chars.toLocaleString()}文字 · ${e.value?e.value.split('\n').length.toLocaleString():0}行`;const n=Array.from(e.value.slice(range.start,range.end)).length;$('scope').textContent=n?`選択 ${n}文字が対象`:'全文が対象';$('undo').disabled=!past.length;$('redo').disabled=!future.length;$('copy').disabled=!e.value}
function push(s){past.push(s);while(past.length>100||past.reduce((n,x)=>n+x.text.length,0)>12000000){if(past.length===1)break;past.shift()}}
function flush(){clearTimeout(timer);if(e.value!==committed.text){push(committed);future=[];committed=snapshot();persist();update()}}
function commit(text,start,end){flush();if(text===e.value){notify('変更はありません');return false}push(snapshot());future=[];const scroll=e.scrollTop;let a=0,b=e.value.length,c=text.length;while(a<b&&a<c&&e.value[a]===text[a])a++;while(b>a&&c>a&&e.value[b-1]===text[c-1]){b--;c--}e.setRangeText(text.slice(a,c),a,b,'preserve');e.setSelectionRange(start,end);e.scrollTop=scroll;range={start,end};committed=snapshot();persist();update();return true}
function restore(s){e.value=s.text;e.setSelectionRange(s.start,s.end);e.scrollTop=s.scroll;range={start:s.start,end:s.end};committed=snapshot();persist();update()}
function history(redo){if(composing)return;closeSheet();flush();const from=redo?future:past,to=redo?past:future;if(!from.length)return;to.push(snapshot());restore(from.pop());notify(redo?'やり直しました':'元に戻しました');}
function notify(message,undo=false){clearTimeout(toastTimer);$('toast').hidden=false;$('toast').querySelector('span').textContent=message;$('toastUndo').hidden=!undo;toastTimer=setTimeout(()=>$('toast').hidden=true,3500)}
function bounds(){return range.end>range.start?{...range}:{start:0,end:e.value.length}}
function apply(id){if(composing)return;const b=target||bounds(),r=WorkbenchTransforms.transform(e.value.slice(b.start,b.end),id);const text=e.value.slice(0,b.start)+r.text+e.value.slice(b.end);const selected=b.end>b.start&&range.end>range.start;if(commit(text,selected?b.start:Math.min(range.start,text.length),selected?b.start+r.text.length:Math.min(range.start,text.length))){notify(`${r.label} · ${r.count.toLocaleString()}か所`,true)}closeSheet();}
function closeSheet(){if($('sheet').hidden)return;$('sheet').hidden=true;$('shade').hidden=true;document.querySelector('header').inert=false;document.querySelector('.work').inert=false;document.querySelector('footer').inert=false;target=null;if(returnFocus&&returnFocus!==e)returnFocus.focus({preventScroll:true})}
function openSheet(name,trigger){if(composing){notify('文字の入力を確定してから操作してください');return}flush();capture();target=bounds();returnFocus=trigger||document.activeElement;$('sheetTitle').textContent=name;$('sheetScope').textContent=range.end>range.start?`選択 ${Array.from(e.value.slice(range.start,range.end)).length}文字が対象`:'全文が対象';const p=$('panel');p.replaceChildren();
if(name==='置換'){p.innerHTML='<label for="find">検索文字列</label><input id="find" type="text" autocomplete="off" autocapitalize="off" spellcheck="false"><label for="replacement">置換文字列</label><input id="replacement" type="text" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="空欄なら削除"><p id="matches" aria-live="polite"></p><div class="row"><button id="nextFind">次を検索</button><button id="nextReplace">次を置換</button></div><div class="row"><button class="strong" id="allReplace">すべて置換</button></div><details><summary>詳細設定</summary><label><input id="case" type="checkbox" checked>大文字・小文字を区別</label></details>';$('find').value=e.value.slice(range.start,range.end);let cursor=0;function matches(){const query=$('find').value,body=e.value.slice(target.start,target.end);if(!query)return [];const sensitive=$('case').checked;const hay=sensitive?body:body.toLowerCase(),needle=sensitive?query:query.toLowerCase();let found=[],i=0;while((i=hay.indexOf(needle,i))!==-1){found.push(i);i+=needle.length}return found}function count(){cursor=0;$('sheetScope').textContent=range.end>range.start?`選択 ${Array.from(e.value.slice(target.start,target.end)).length}文字が対象`:'全文が対象';const m=matches();$('matches').textContent=$('find').value?`${m.length.toLocaleString()}件が該当`:'検索文字列を入力';for(const id of ['nextFind','nextReplace','allReplace'])$(id).disabled=!m.length}for(const id of ['find','case'])$(id).addEventListener('input',count);$('nextFind').onclick=()=>{const m=matches();if(!m.length)return;const i=m[cursor++%m.length];e.setSelectionRange(target.start+i,target.start+i+$('find').value.length);notify(`${(cursor-1)%m.length+1} / ${m.length}件目`)};function replace(all){const m=matches();if(!m.length)return;const q=$('find').value,r=$('replacement').value,b={...target},body=e.value.slice(b.start,b.end);const chosen=all?m:[m[(Math.max(0,cursor-1))%m.length]];let out=body;for(const i of chosen.slice().reverse())out=out.slice(0,i)+r+out.slice(i+q.length);const text=e.value.slice(0,b.start)+out+e.value.slice(b.end);if(commit(text,b.start,b.start+out.length)){notify(`${chosen.length}件を置換`,true);target={start:b.start,end:b.start+out.length};count()}}$('nextReplace').onclick=()=>replace(false);$('allReplace').onclick=()=>replace(true);count();}
else if(name==='その他'){const clear=document.createElement('button');clear.className='action';clear.textContent='全文を削除';clear.onclick=()=>{if(!window.confirm('本文をすべて削除しますか？'))return;if(commit('',0,0))notify('全文を削除しました',true);persist();closeSheet()};p.append(clear);const note=document.createElement('p');note.className='note';note.textContent='本文は外部へ送信しません。このブラウザ内で加工し、閉じても復元できるよう自動退避します。全文削除で退避データも消えます。Safariの共有メニューから「ホーム画面に追加」できます。';p.append(note)}
else{const ids={空白:['spaces','tabs','trim'],改行:['blank','collapse','newlines'],文字:['width']}[name];for(const id of ids){const b=document.createElement('button');b.className='action';const label=document.createElement('span');label.textContent=WorkbenchTransforms.definitions[id][0];const arrow=document.createElement('span');arrow.textContent='→';b.append(label,arrow);b.onclick=()=>apply(id);p.append(b)}}
$('sheet').hidden=false;$('shade').hidden=false;document.querySelector('header').inert=true;document.querySelector('.work').inert=true;document.querySelector('footer').inert=true;requestAnimationFrame(()=>$('close').focus({preventScroll:true}));}
e.addEventListener('compositionstart',()=>{flush();composing=true});e.addEventListener('compositionend',()=>{composing=false;capture();flush()});e.addEventListener('beforeinput',()=>{if(!composing&&e.value===committed.text)committed=snapshot()});e.addEventListener('input',()=>{capture();update();if(!composing){clearTimeout(timer);timer=setTimeout(flush,500);persist()}});for(const event of ['select','keyup','pointerup','focus'])e.addEventListener(event,capture);document.addEventListener('selectionchange',capture);
for(const b of document.querySelectorAll('[data-panel]')){b.addEventListener('pointerdown',capture);b.onclick=()=>openSheet(b.dataset.panel,b)}
$('close').onclick=closeSheet;$('shade').onclick=closeSheet;$('undo').onclick=()=>history(false);$('redo').onclick=()=>history(true);$('toastUndo').onclick=()=>history(false);
$('copy').onclick=async()=>{if(composing){notify('文字の入力を確定してから操作してください');return}const text=e.value;try{await navigator.clipboard.writeText(text);notify(`${Array.from(text).length.toLocaleString()}文字をコピー`)}catch{const s=snapshot();e.focus({preventScroll:true});e.select();const ok=document.execCommand('copy');e.setSelectionRange(s.start,s.end);e.scrollTop=s.scroll;notify(ok?`${Array.from(text).length}文字をコピー`:'本文を長押ししてコピーしてください')}};
$('paste').onclick=async()=>{if(composing)return;capture();const b={...range};try{const text=await navigator.clipboard.readText();if(commit(e.value.slice(0,b.start)+text+e.value.slice(b.end),b.start+text.length,b.start+text.length))notify('貼り付けました',true);e.focus({preventScroll:true})}catch{e.focus({preventScroll:true});notify('本文を長押しして「ペースト」を選んでください')}};
document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeSheet();return}if(!$('sheet').hidden&&event.key==='Tab'){const nodes=[...$('sheet').querySelectorAll('button:not(:disabled),input,summary')].filter(n=>n.getClientRects().length),first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='z'&&document.activeElement===e&&!composing){event.preventDefault();history(event.shiftKey)}});
function viewport(){const v=window.visualViewport;document.documentElement.style.setProperty('--vh',`${v?v.height:window.innerHeight}px`);document.documentElement.style.setProperty('--top',`${v?v.offsetTop:0}px`);document.body.classList.toggle('keyboard',!!v&&window.innerHeight-v.height>120)}if(window.visualViewport){visualViewport.addEventListener('resize',viewport);visualViewport.addEventListener('scroll',viewport)}window.addEventListener('resize',viewport);window.addEventListener('pagehide',()=>{flush();persist()});document.addEventListener('visibilitychange',()=>{if(document.hidden){flush();persist()}else viewport()});window.addEventListener('pageshow',viewport);
try{e.value=localStorage.getItem(key)||'';if(e.value)notify('前回の本文を復元しました')}catch{}committed=snapshot();update();viewport();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
